apiVersion: v1
kind: Service
metadata:
  name: workspaces-controller-metrics-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: controller-manager
