apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- istio-authorization-policy.yaml
- destination-rule.yaml
- virtual-service.yaml

components:
- ../common/naming-component

replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: frontend
    version: v1
  targets:
  - fieldPaths:
    - spec.http.0.route.0.destination.host
    options:
      delimiter: .
    select:
      group: networking.istio.io
      kind: VirtualService
      name: frontend
      version: v1alpha3
  - fieldPaths:
    - spec.http.1.route.0.destination.host
    options:
      delimiter: .
    select:
      group: networking.istio.io
      kind: VirtualService
      name: frontend
      version: v1alpha3
  - fieldPaths:
    - spec.host
    options:
      delimiter: .
    select:
      group: networking.istio.io
      kind: DestinationRule
      name: frontend
      version: v1alpha3
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: frontend
    version: v1
  targets:
  - fieldPaths:
    - spec.http.0.route.0.destination.host
    options:
      delimiter: .
      index: 1
    select:
      group: networking.istio.io
      kind: VirtualService
      name: frontend
      version: v1alpha3
  - fieldPaths:
    - spec.http.1.route.0.destination.host
    options:
      delimiter: .
      index: 1
    select:
      group: networking.istio.io
      kind: VirtualService
      name: frontend
      version: v1alpha3
  - fieldPaths:
    - spec.host
    options:
      delimiter: .
      index: 1
    select:
      group: networking.istio.io
      kind: DestinationRule
      name: frontend
      version: v1alpha3
- source:
    fieldPath: spec.ports.[name=http-frontend].port
    kind: Service
    name: frontend
    version: v1
  targets:
  - fieldPaths:
    - spec.http.0.route.0.destination.port.number
    select:
      group: networking.istio.io
      kind: VirtualService
      name: frontend
      version: v1alpha3
  - fieldPaths:
    - spec.http.1.route.0.destination.port.number
    select:
      group: networking.istio.io
      kind: VirtualService
      name: frontend
      version: v1alpha3
