name: Trivy FS scanning

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6:00 AM UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to scan'
        required: true
        default: 'notebooks-v1'
        type: choice
        options:
          - notebooks-v1
          - notebooks-v2

permissions:
  actions: read
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', github.event.inputs.branch)) || fromJSON('["notebooks-v1", "notebooks-v2"]') }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        scanners: 'vuln,secret,misconfig'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        exit-code: 0
        output: 'trivy-fs-scan-results-${{ matrix.branch }}.sarif'

    - name: Add branch metadata to SARIF
      run: |
        # Add category and modify ruleId to include branch information
        jq '.runs[0].results[] |= (.category = "trivy-fs-scan-${{ matrix.branch }}" | .ruleId = "trivy-fs-${{ matrix.branch }}-" + .ruleId)' \
           trivy-fs-scan-results-${{ matrix.branch }}.sarif > trivy-fs-scan-results-${{ matrix.branch }}-processed.sarif
        mv trivy-fs-scan-results-${{ matrix.branch }}-processed.sarif trivy-fs-scan-results-${{ matrix.branch }}.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: 'trivy-fs-scan-results-${{ matrix.branch }}.sarif'