name: Trivy FS scanning

on:
  schedule:
    - cron: '0 6 * * 0'  # Every Sunday at 6:00 AM UTC
  workflow_dispatch:

permissions:
  actions: read
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        scanners: 'vuln,secret,misconfig'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true
        exit-code: 0
        output: 'trivy-fs-scan-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
          sarif_file: 'trivy-fs-scan-results.sarif'