name: Build & Publish Backend container image
on:
  push:
    branches:
      - main
      - notebooks-v2
      - v*-branch
    paths:
      - workspaces/**    ## NOTE: we publish changes on any commit to workspaces/ components
      - releasing/version/VERSION

env:
  REGISTRY: ghcr.io/kubeflow/notebooks
  NAME: workspaces-backend

jobs:
  push_to_registry:
    name: Build & Push container image to GHCR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push multi-arch container image
      run: |
        cd workspaces/backend
        make docker-buildx REGISTRY=${REGISTRY} NAME=${NAME}

    - name: Build and push multi-arch container image on Version change
      if: steps.filter.outputs.version == 'true'
      run: |
        VERSION=$(cat releasing/version/VERSION)
        cd workspaces/backend
        make docker-buildx REGISTRY=${REGISTRY} NAME=${NAME} TAG=${VERSION}
